DFE-Digital/get-help-with-remote-education

source/robots.txt

Added robots.txt to disallow all routes for search engine indexing

added robots.txt

---

.github/workflows/deploy_to_prod.yml

Added basic auth to production env to prevent web crawlers

added basic auth to prod

---

.gitignore
Gemfile
Gemfile.lock
source/assets/javascripts/cookie_consent.js
source/assets/javascripts/cookie_helper.js
source/assets/javascripts/google_analytics.js
source/layouts/layout.erb

Why: 
Added google analytics to track page views
How: 
Stored GA measurement ID as an env variable and load scripts if the variable exists.
Check for user consent, if present add ga cookies.

added Gtag

---

source/assets/javascripts/cookie_helper.js

Update `allowAnalyticsCookies` to check the value of the cookie consent to make sure users have opted in﻿

Fix analytics consent condition

---

.github/workflows/deploy_to_dev.yml

added ga id env variable

---

package-lock.json
package.json
source/assets/javascripts/cookie_consent.js
source/assets/javascripts/cookie_helper.js
source/assets/javascripts/google_analytics.js
source/layouts/layout.erb

Added async script tag and disable ga cookies when consent isn't provided as per:
https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out

added fix for analytics cookies

---

source/cookie_preferences.html.erb
source/layouts/layout.erb

- Add cookie policy content
- Add link to the cookie page to the footer

Add content to the cookie policy page

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_prod.yml
.github/workflows/deploy_to_staging.yml

3 changes:
1. Added basic auth to dev and staging environments
2. Renamed actions job to match env
3. Moved GA env var to prod only

added basic auth and move ga to prod

---

source/nginx/conf/includes/cache.conf
source/nginx/conf/includes/custom_headers.conf

Added security headers to one location

added all headers to cache config

---

source/nginx/conf/includes/cache.conf

Remove location block entirely

remove location for caching

---

source/assets/javascripts/cookie_consent.js
source/assets/javascripts/google_analytics.js

added check for existing ga cookies

---

source/good-teaching-practice.html.erb
source/layouts/layout.erb
source/safeguarding.html.erb
source/send.html.erb
source/statutory-obligations.html.erb
source/support-for-recovery.html.erb

- Add statutory obligations content
- Add good teaching practice page
- Add safeguarding page
- Add SEND content
- Add recovery support content
- Add page titles

Add content to pages

---

source/assets/stylesheets/partials/_cards.scss
source/index.html.erb

Changes:
1. Update content to latest version
2. Fix card tile height

Update homepage content

---

source/assets/javascripts/google_analytics.js

Add GA tracking to external link clicks that's initialised alongside the rest of the analytics﻿

Add GA tracking to external links

---

source/assets/stylesheets/partials/_cards.scss

Removed min height css property on cards for mobile devices

removed min height for mobile devices

---

source/accessibility-statement.html.erb
source/assets/stylesheets/partials/_index.scss
source/assets/stylesheets/partials/_typography.scss
source/layouts/layout.erb

**Note: Draft until placeholder information is added**
- Add accessibility statement with placeholder dates/emails
- Add accesibility statement to footer

Add Accessibility statement

---

source/nginx/conf/includes/error_page.conf
source/not-found.html.erb

Added custom 404 for pages not found. 
Included a link to ghre-feedback@digital.education.gov.uk

added custom 404

---

source/not-found.html.erb

added email

---

.github/workflows/deploy_to_prod.yml
.github/workflows/deploy_to_staging.yml

Added default working directory for prod and staging pipelines for deploying static site

updated staging and prod pipelines

---

ghre-static/source/assets/stylesheets/partials/_cards.scss

Set media query to adjust card height for mid sized devices

added card height for tablets

---

ghre-rails/Gemfile
ghre-rails/Gemfile.lock
ghre-rails/app/views/pages/_date_badge.html.erb
ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/webpacker/styles/partials/_cards.scss
ghre-rails/config/locales/en.yml
ghre-rails/spec/controllers/pages_controller_spec.rb
ghre-rails/spec/features/view_pages_spec.rb
ghre-rails/spec/views/pages/date_badge_spec.rb

- Add partials for date badge on index page
- Added placeholder dates to en.yml
- Added relevant styles to _cards.scss
- Added unit tests

Add date partials

---

ghre-rails/app/views/pages/good_teaching_practice.html.erb

- Add resources links to rails app

align content

---

ghre-rails/app/controllers/pages_controller.rb
ghre-rails/app/views/errors/internal_server_error.html.erb
ghre-rails/app/views/errors/not_found.html.erb
ghre-rails/app/views/errors/unprocessable_entity.html.erb
ghre-rails/config/environments/production.rb
ghre-rails/config/routes.rb
ghre-rails/spec/requests/errors_request_spec.rb
ghre-rails/spec/requests/pages_request_spec.rb

- update error routing
- add back links to error pages
- add static asset caching

Prep for rails deploy

---

ghre-rails/Dockerfile

fix alpine to 3.12

---

.github/workflows/deploy_rails_to_prod.yml

- set deployment strategy to rolling

add rolling strategy

---

ghre-rails/.gitignore
ghre-rails/app/views/layouts/application.html.erb

- ignore self signed certificates for https testing on localhost
- add gtm

add gtm scripts

---

.github/workflows/deploy_rails_to_dev.yml
.github/workflows/deploy_rails_to_prod.yml
.github/workflows/deploy_rails_to_staging.yml
.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_prod.yml
.github/workflows/deploy_to_staging.yml
docs/upload_to_s3.md
terraform/variables.tf

The dfe-teacher-services paas organisation will be renamed to dfe at 3pm on 25 Jan. This should be merged afterwards.

Rename paas organisation

---

ghre-rails/app/views/pages/good_teaching_practice.html.erb

add updated event link

---

ghre-rails/app/views/settings/cookie_preferences.html.erb

add ua cookie

---

ghre-rails/app/views/settings/cookie_preferences.html.erb

add additional cookie to policy

---

ghre-rails/app/views/pages/_links_with_topics.html.erb
ghre-rails/app/views/pages/good_teaching_practice.html.erb
ghre-rails/config/locales/en.yml
ghre-rails/spec/features/pages/good_teaching_practice_spec.rb
ghre-rails/spec/views/pages/links_with_topics_spec.rb

20210127 content updates

---

ghre-rails/app/views/pages/good_teaching_practice.html.erb

update online event text

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/config/routes.rb
ghre-rails/spec/requests/pages_request_spec.rb
ghre-rails/spec/routes/routes_spec.rb

Add home page redirects

---

ghre-rails/config/manifests/dev_manifest.yml

add pg service

---

docs/govuk_paas.md

Add gov paas docs

---

docs/govuk_paas.md

fix formatting

---

ghre-rails/app/helpers/view_helper.rb
ghre-rails/app/views/pages/good_teaching_practice.html.erb
ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/views/pages/safeguarding.html.erb
ghre-rails/app/webpacker/styles/partials/_typography.scss
ghre-rails/config/locales/en.yml
ghre-rails/spec/features/index_spec.rb
ghre-rails/spec/helpers/view_helper_spec.rb

20210211 content updates

---

ghre-rails/app/views/layouts/_cookie_banner.html.erb

- fix broken 'collect information' link

fix broken link

---

terraform/workspace-variables/dev.tfvars
terraform/workspace-variables/prod.tfvars

- update testing endpoint for status cake

update statuscake test url

---

ghre-rails/app/views/layouts/_cookie_banner.html.erb
ghre-rails/app/views/layouts/_cookie_banner_accepted.html.erb
ghre-rails/app/views/layouts/application.html.erb
ghre-rails/app/webpacker/packs/cookie_banner.js
ghre-rails/app/webpacker/packs/cookie_banner_accept.js
ghre-rails/app/webpacker/styles/partials/_layout.scss

- Refresh page immdiately following cookie accept click, to increase amount of data for BA

Immediate analytics after cookie accept

---

ghre-rails/app/views/pages/good_teaching_practice.html.erb

- New early years section
- Rework headings & structure

New early years section, rework sub-sections

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/views/pages/send.html.erb
ghre-rails/config/locales/en.yml

- Entirely new content for SEND page
- Add vulnerable children content to SEND page.

New SEND page content, add VC content.

---

ghre-rails/app/views/pages/videos_webinars.html.erb
ghre-rails/config/locales/en.yml

- Videos page - new cyber security section

videos_webinars - new cyber security section

---

docs/govuk_paas.md
ghre-rails/config/manifests/dev_manifest.yml
ghre-rails/config/manifests/prod_manifest.yml
ghre-rails/config/manifests/staging_manifest.yml

- Remove logit log capture service - cost cutting as not used at all, service not interactive.

Remove logit

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/webpacker/styles/partials/_layout.scss

- New header tile on homepage for Sandringham training.

Home page - Sandringham tile

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/views/pages/support_for_recovery.html.erb
ghre-rails/app/webpacker/styles/partials/_layout.scss
ghre-rails/config/locales/en.yml

- Update National Tutoring Programme guidance

Update National Tutoring Programme guidance

---

ghre-rails/app/views/pages/videos_webinars.html.erb
ghre-rails/config/locales/en.yml

- Replace NCSC webinar link with steaming link as now passed
- Update updated

Replace NCSC webinar link with steaming link as now passed

---

ghre-rails/app/views/pages/statutory_obligations.html.erb
ghre-rails/app/webpacker/styles/partials/_typography.scss
ghre-rails/config/locales/en.yml
ghre-rails/spec/features/pages/statutory_obligations_spec.rb

- Rewritten statutory obligations and expectations page

Rewritten statutory obligations and expectations page

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/views/pages/support_for_recovery.html.erb
ghre-rails/config/locales/en.yml
ghre-rails/spec/features/pages/support_for_recovery_spec.rb

- Rewrite of, and new title for support page

Rewrite of, and new title for support page

---

README.md
ghre-rails/app/views/pages/good_teaching_practice.html.erb

While trying to set this repo up for the first time I found the instructions were incomplete. I've updated them to better reflect how one can get the code running locally

Minor tidy up and first commit

---

ghre-rails/app/views/pages/good_teaching_practice.html.erb
ghre-rails/app/views/pages/safeguarding.html.erb

This is to update two links in the service, as previous links were broken

Update two links

---

ghre-rails/app/views/pages/index.html.erb
ghre-rails/app/views/pages/send.html.erb
ghre-rails/app/views/pages/statutory_obligations.html.erb
ghre-rails/app/views/pages/videos_webinars.html.erb
ghre-rails/config/locales/en.yml

Link to statutory guidance has been updated
New para detailing schools' obligations
A new paragraph has been added
The case study by Sandringham School has been moved to this area and deleted from the front page

Various content updates
